sudo: required
services:
    - docker

# before_install:
#     - docker build -t inyps2/docker-angular -f Dockerfile.dev .
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-angular"
    env: "DockerAngular-env"
    bucket_name: "elasticbeanstalk-us-east-1-079110273152"
    bucket_path: "docker-angular"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"